language: csharp
solution: UnitTest_Nunit_Triangle.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore UnitTest_Nunit_Triangle.sln
after_script:
  - nunit-console UnitTest_Nunit_Triangle.Test/bin/Release/UnitTest_Nunit_Triangle.Test.dll